management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
info:
  env:
    enabled: true

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: movieQueue
  serie:
    name: serieQueue
  catalog:
    name: catalogQueue
    
  management:
    endpoints:
      web:
        exposure:
          include=circuitbreakers,circuitbreakerevents,health,info,ratelimiters,metrics
    health:
      circuitbreakers:
        enabled: true
    endpoint:
      health:
        show-details: always

  resilience4j:
    circuitbreaker:
      instances: 
        review:
          allowHealthIndicatorToFail: false
          registerHealthIndicator: true
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 15000
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true
