spring:
  application:
    name: movie-service
  config:
    import:
      - optional:configserver:http://localhost:8888/
  profiles:
    active: dev
server:
  port : 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQL5Dialect
    # show-sql: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=1;
    username: sa
    password: sa

  sql:
    init:
      dataLocations: classPath:/movie-service.sql
